#ifndef APPLICATION_USER_SCREENS_INC_MAIN_PANEL_H_
#define APPLICATION_USER_SCREENS_INC_MAIN_PANEL_H_

#include "DIALOG.h"

#define ID_WINDOW_MAIN  	(GUI_ID_USER + 0x00)
#define ID_EXIT_BUTTON 		(GUI_ID_USER + 0x01)
#define ID_SLIDER_SPEED  	(GUI_ID_USER + 0x02)
#define ID_SLIDER_RPM  		(GUI_ID_USER + 0x03)
#define ID_TEXT_SPEED	  	(GUI_ID_USER + 0x04)
#define ID_TEXT_RPM  		(GUI_ID_USER + 0x05)
#define ID_RADIO_STATUS  	(GUI_ID_USER + 0x06)
#define ID_BUTTON_UP  		(GUI_ID_USER + 0x07)
#define ID_BUTTON_RIGHT  	(GUI_ID_USER + 0x08)
#define ID_BUTTON_LEFT  	(GUI_ID_USER + 0x09)
#define ID_BUTTON_DOWN  	(GUI_ID_USER + 0x0A)
#define ID_BUTTON_OK  		(GUI_ID_USER + 0x0B)
#define ID_RADIO_PERIODIC  	(GUI_ID_USER + 0x0C)

void mainCallback(WM_MESSAGE *pMsg);

#endif /* APPLICATION_USER_SCREENS_INC_MAIN_PANEL_H_ */
