#ifndef APPLICATION_USER_CORE_INC_SPISCREEN_H_
#define APPLICATION_USER_CORE_INC_SPISCREEN_H_

#include "DIALOG.h"

#define ID_WINDOW_SPI  (GUI_ID_USER + 0x00)
#define ID_MULTIEDIT_SPI  (GUI_ID_USER + 0x01)

void _cbSPIDialog(WM_MESSAGE * pMsg);

#endif /* APPLICATION_USER_CORE_INC_SPISCREEN_H_ */
